import os

API_KEY = os.environ.get("LAYA_API_KEY")

if not API_KEY:
    raise RuntimeError("LAYA_API_KEY is not set")

MAX_STATE_BYTES = 50_000
MAX_QUESTIONS = 100
MAX_QUESTION_ID_LENGTH = 100
MAX_INSTRUCTIONS_LENGTH = 2_000
MAX_OPTION_COUNT = 50
MAX_OPTION_LENGTH = 500
MAX_OPTION_DESCRIPTION_LENGTH = 2_000
